name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or whatever Node version you used locally

    - name: Install dependencies
      run: npm install

    - name: Build Core App
      run: |
        cd core-app
        npm install
        npm run build

    - name: Build Remote App
      run: |
        cd ../remote-app
        npm install
        npm run build

    - name: Run Tests (Optional)
      run: |
        cd ../core-app
        npm run test -- --coverage
