name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  

    - name: Install dependencies for Core App
      run: |
        cd mf-core-app
        npm install

    - name: Build Core App
      run: |
        cd mf-core-app
        npm run build

    - name: Install dependencies for Remote App
      run: |
        cd mf-remote-app
        npm install

    - name: Build Remote App
      run: |
        cd mf-remote-app
        npm run build

    - name: Run Tests (Optional)
      run: |
        cd mf-core-app
        npm run test -- --coverage
